### ISSUE TITLE
Design Docs

### ISSUE THREAD

**Issue by darreneid** [Asyan77/Burnr#1]
# Wiki Home Page
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
  - [x] each wiki page is listed in bullet points
  - [x] all links route the correct page
## Comments
---
# MVP Feature List
- [x] Should have 7 total features
  - [x] 3 of those are User Auth, Hosting, and Production README.
  - [x] The other 4 are unique to the specific app
- [x] Contains a description sentence of the app
- [ ] Includes two to three detailed bullets on functionality and presentation of feature
- [ ] Two CRUD features
- [ ] Estimates how long it will take the code each feature
- [x] Correctly formatted
  - [x] Features are listed in an ordered list
  - [x] Each feature is broken down into bullet points
## Comments
---
# Database Schema
- [x] Contains correct datatypes
- [ ] Contains appropriate constraints/details
  - [x] primary key
  - [x] not null
  - [ ] unique
  - [x] indexed
  - [x] foreign key
- [ ] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
- [x] foreign key and table name are lowercased, snake_cased, and `back_ticked`
- [x] Correctly formatted
  - [x] schema is written in a table format
  - [x] the table’s name are lowercased, snake_cased and `back_ticked`
  - [x] the table header column names are bolded
  - [x] columns names are lowercased and snaked_cased and `back_ticked`
## Comments
---
# Sample State
- [x] State shape is flat
- [ ] State’s keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [ ] Correctly formatted
  - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [ ] Top level slices
    - [ ] `entities`
    - [x] `session`
    - [x] `errors` (here or in `ui`)
    - [x] `ui` (if needed)
  - [x] Should NOT have nested slices, aka `comments` inside of `posts`
## Comments
---
# Backend Routes
- [x] Contains the following sections: HTML, API Endpoints (Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Does not contain superfluous routes
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes
## Comments
---
# Frontend Routes
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
  - [x] Routes are displayed with `inline coding text` (backticks)
## Comments

**Comment by taylormusolf** [comment]
@Asyan77 On your Feature List, I would note for `Photostream` feature that 'users can upload, edit, and delete photos' as well. 
For the Schema doc, don't forget `password_digest` for `users`.  `photos` and `albums` should have a `belongs_to: owner` not a `has_one`.  You will need a way to connect `albums` to `photos` which is a many-to-many relationship so you would need a joins table that could be called `photo_albums`.  
For your sample state, I think the `entities` key might have been left out of your copy paste.  Otherwise looks good. If you end up making any schema updates like adding the suggested joins table then make sure to update the sample state as well.

Let me know if you have any questions or if you make any updates.

**Comment by taylormusolf** [comment]
@Asyan77 Just did another pass.  I noticed in your Schema, for the `comments` table that you have a `unique: true` on `user_id` and `photo_id` combination.  That would mean though a user could only ever comment on a photo once, which I am not sure if that is what you would want to be the case.

For your State Shape, make sure all keys are camelCased.  You should also include any image urls that you will need.

Backend routes look pretty good.  I would say you should mention though which routes will be fetching `likes` and `comments` though since they don't have their own GET routes.  Also you will need to update this doc once you address how you are connecting a photo to an album.
